\ProvidesClass{apecdigest}

\PassOptionsToClass{letterpaper}{article}%
\LoadClassWithOptions{article} % 12pt preferred, 10pt is minimum
\RequirePackage[margin=1in]{geometry}
\RequirePackage[english]{babel}

\RequirePackage{mathptmx}

\RequirePackage{setspace}
\doublespacing

% Only allow figures on extra pages
%\renewcommand{\topfraction}{.001}
%\setcounter{topnumber}{0}
%\setcounter{bottomnumber}{0}
%\setcounter{totalnumber}{0}
%\renewcommand{\bottomfraction}{.001}

%\renewcommand{\topfraction}{.85}%(=Maximum fraction of the page that can be occupied by floats at the top of the page)
%\renewcommand{\bottomfraction}{.85}

%\RequirePackage[format=hang,justification=justified,font=sf,labelfont=bf,singlelinecheck=false]{caption}

%\RequirePackage{subfigure}

%\clubpenalty = 10000
%\widowpenalty = 10000
%\displaywidowpenalty = 10000

\endinput